name: Cypress Tests

on: [push]

jobs:
  cypres-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          test: yarn cypress:headless
